id: P004300
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:08:48.249284
source_metadata:
  id: bdr:W20016
  title: གྲང་བའི་ནད་ཀྱི་རྣམ་བཤད
  author: ''
  volumes:
    4081ecd659cb4b41b072938e90c85c21:
      image_group_id: I1PD28060
      title: ''
      volume_number: 1
      total_pages: 216
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
